apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: couchbase-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rhadaway14/proto-gemcouch
    targetRevision: main
    path: gitops/couchbase
  destination:
    server: https://kubernetes.default.svc
    namespace: pgc-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
